export default function getAllProducts() {
  return [
    {
      id: 'FD-004',
      slug: 'rendang-daging',
      name: 'Rendang Daging',
      category: 'Main Course',
      categorySlug: 'main-course',
      price: 50_000,
      stock: 10,
      imageUrl: '/assets/images/rendang-daging.jpeg',
      description: `Slow-cooked beef in a rich and spicy coconut milk sauce, a popular dish from Minangkabau cuisine.`,
    },
    {
      id: 'FD-001',
      slug: 'nasi-goreng-special',
      name: 'Nasi Goreng Special',
      category: 'Main Course',
      categorySlug: 'main-course',
      price: 35_000,
      stock: 20,
      imageUrl: '/assets/images/nasi-goreng-special.jpg',
      description: `A classic Indonesian fried rice dish cooked with special spices, chicken, shrimp, and a sunny-side-up egg on top.`,
    },
    {
      id: 'FD-002',
      slug: 'sate-ayam-madura',
      name: 'Sate Ayam Madura',
      category: 'Appetizer',
      categorySlug: 'appetizer',
      price: 30_000,
      stock: 15,
      imageUrl: '/assets/images/sate-ayam-madura.jpg',
      description: `Delicious skewered chicken served with a rich peanut sauce and a side of sweet soy sauce.`,
    },
    {
      id: 'FD-003',
      slug: 'gado-gado',
      name: 'Gado-Gado',
      category: 'Salad',
      categorySlug: 'salad',
      price: 28_000,
      stock: 25,
      imageUrl: '/assets/images/gado-gado.jpg',
      description: `A traditional Indonesian salad made with boiled vegetables, tofu, tempeh, and eggs, topped with a flavorful peanut sauce.`,
    },
    {
      id: 'FD-005',
      slug: 'es-cendol',
      name: 'Es Cendol',
      category: 'Dessert',
      categorySlug: 'dessert',
      price: 15_000,
      stock: 30,
      imageUrl: '/assets/images/es-cendol.jpg',
      description: `A refreshing traditional Indonesian dessert made with rice flour jelly, coconut milk, and palm sugar syrup.`,
    },
  ];
}
